CR EQU 0X0D
	AREA Program,CODE,READONLY
ENTRY
MAIN
	LDR R1, = TABLE
	LDR R4, = StrLen
	EOR R5,R5,R5
LOOP LDRB R2, [R1],#1
	 CMP R2, #CR
	 BEQ DONE
	 ADD R5,R5,#01
	 BAL LOOP
DONE STR R5,[R4]
STOP B STOP
TABLE DCB "WORLD",CR
	AREA RESULT,DATA,READWRITE
StrLen DCB 0xD
END